### ISSUE TITLE
Create script to locally run all the pipeline checks we want to do for each PR

### ISSUE THREAD

**Issue by robert-northmind** [bmw-tech/widget_driver#5]
We should add an action that t least builds and runs tests for all PRs before they are allowed to me merged.

Here is an example of a build action building an ios app
```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # https://github.com/actions/virtual-environments
    runs-on: macos-11

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Test MyThing
        timeout-minutes: 10
        run: |
          set -o pipefail && xcodebuild -workspace MyThing.xcodeproj/project.xcworkspace -scheme MyNetworking -destination 'platform=iOS Simulator,name=iPhone 12' test | xcpretty
      
      - name: Test MyThing-watch
        timeout-minutes: 10
        run: |
          fastlane scan
```
