### ISSUE TITLE
Change pubspec dependencies to not use `path`

### ISSUE THREAD

**Issue by robert-northmind** [bmw-tech/widget_driver#66]
**Describe the bug**
Currently our package import the other widget_driver packages via `path` in the pubspec.yaml.
We should change this to import them correctly.. from pub.dev.. since now the packages are published to pub.dev

And then we should also update all the analysis_options.yaml and remove the 

```yaml
analyzer:
  errors:
    invalid_dependency: ignore
```

Since that would then no longer be needed
